export interface FormulaResult {
  formula:     string;
  explanation: string;
  breakdown:   { part: string; description: string }[];
  example:     string;
  tips:        string[];
}

// ── TXT export ────────────────────────────────────────────────────────────────

export function exportToTxt(result: FormulaResult, description: string): void {
  const now = new Date().toLocaleString();
  const lines = [
    "═══════════════════════════════════════════════════════",
    "  AI FORMULA GENERATOR — Formula Report",
    `  Generated: ${now}`,
    "═══════════════════════════════════════════════════════",
    "",
    "YOUR REQUEST",
    "────────────",
    description,
    "",
    "EXCEL FORMULA",
    "─────────────",
    result.formula,
    "",
    "HOW IT WORKS",
    "────────────",
    result.explanation,
    "",
  ];

  if (result.breakdown?.length) {
    lines.push("FORMULA BREAKDOWN", "─────────────────");
    for (const b of result.breakdown) {
      lines.push(`  • ${b.part}`);
      lines.push(`    ${b.description}`);
    }
    lines.push("");
  }

  if (result.example) {
    lines.push("EXAMPLE", "───────", result.example, "");
  }

  if (result.tips?.length) {
    lines.push("TIPS", "────");
    for (const t of result.tips) lines.push(`  ✓ ${t}`);
    lines.push("");
  }

  lines.push(
    "═══════════════════════════════════════════════════════",
    "  Generated by AI Formula Generator — Excel Add-in",
    "═══════════════════════════════════════════════════════",
  );

  const text = lines.join("\n");
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = "formula.txt";
  a.click();
  URL.revokeObjectURL(url);
}

// ── PDF export (print-to-PDF via new window) ──────────────────────────────────

export function exportToPdf(result: FormulaResult, description: string): void {
  const now = new Date().toLocaleString("en-US", { dateStyle: "full", timeStyle: "short" });

  const breakdownRows = (result.breakdown ?? [])
    .map(b => `
      <tr>
        <td style="padding:7px 10px;font-family:monospace;font-size:12px;color:#4f46e5;font-weight:700;white-space:nowrap">${b.part}</td>
        <td style="padding:7px 10px;font-size:12px;color:#374151">${b.description}</td>
      </tr>`)
    .join("");

  const tipsHtml = (result.tips ?? [])
    .map(t => `<li style="margin-bottom:6px;font-size:12px;color:#374151">${t}</li>`)
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Formula Report — AI Formula Generator</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      font-size: 13px; color: #111827; background: #fff;
      padding: 36px 40px;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .header { border-bottom: 3px solid #6366f1; padding-bottom: 14px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
    .logo { font-size: 20px; font-weight: 800; color: #4f46e5; }
    .subtitle { font-size: 11px; color: #6b7280; margin-top: 2px; }
    .date { font-size: 10px; color: #9ca3af; text-align: right; }
    .section { margin-bottom: 22px; }
    .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #6b7280; margin-bottom: 8px; }
    .request-box { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 14px; font-size: 13px; color: #374151; }
    .formula-box {
      background: #eef2ff; border: 2px solid #c7d2fe; border-radius: 8px;
      padding: 16px 18px; font-family: 'Courier New', monospace;
      font-size: 16px; font-weight: 700; color: #3730a3; letter-spacing: .02em;
      word-break: break-all;
    }
    .explanation-box { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 12px 14px; font-size: 13px; color: #374151; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: .06em; color: #9ca3af; padding: 6px 10px; border-bottom: 2px solid #e5e7eb; }
    td { border-bottom: 1px solid #f3f4f6; vertical-align: top; }
    tr:last-child td { border-bottom: none; }
    .example-box { background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 12px 14px; font-size: 12px; color: #92400e; }
    .tips-list { padding-left: 20px; }
    .footer { border-top: 1px solid #e5e7eb; padding-top: 10px; margin-top: 8px; font-size: 10px; color: #9ca3af; display: flex; justify-content: space-between; }
    .print-btn { color: #4f46e5; font-weight: 600; cursor: pointer; }
    @media print { .print-btn { display: none !important; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">⚡ AI Formula Generator</div>
      <div class="subtitle">Excel Formula Report</div>
    </div>
    <div class="date">Generated: ${now}</div>
  </div>

  <div class="section">
    <div class="section-title">Your Request</div>
    <div class="request-box">${description}</div>
  </div>

  <div class="section">
    <div class="section-title">Excel Formula</div>
    <div class="formula-box">${result.formula}</div>
  </div>

  <div class="section">
    <div class="section-title">How It Works</div>
    <div class="explanation-box">${result.explanation}</div>
  </div>

  ${breakdownRows ? `
  <div class="section">
    <div class="section-title">Formula Breakdown</div>
    <table>
      <thead><tr><th>Part</th><th>Description</th></tr></thead>
      <tbody>${breakdownRows}</tbody>
    </table>
  </div>` : ""}

  ${result.example ? `
  <div class="section">
    <div class="section-title">Example</div>
    <div class="example-box">${result.example}</div>
  </div>` : ""}

  ${tipsHtml ? `
  <div class="section">
    <div class="section-title">Tips</div>
    <ul class="tips-list">${tipsHtml}</ul>
  </div>` : ""}

  <div class="footer">
    <span>AI Formula Generator · Excel Add-in</span>
    <span class="print-btn" onclick="window.print()">🖨 Print / Save as PDF</span>
  </div>

  <script>window.addEventListener("load", () => setTimeout(() => window.print(), 400));<\/script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) { alert("Pop-up blocked. Please allow pop-ups to export PDF."); return; }
  win.document.write(html);
  win.document.close();
}
