import { ArrowLeft } from "lucide-react";
import { useLocation } from "wouter";

export default function EulaPage() {
  const [, setLocation] = useLocation();
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-border sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center gap-3">
          <button onClick={() => setLocation("/")} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back
          </button>
          <h1 className="text-sm font-bold">End-User License Agreement</h1>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8 space-y-6 text-sm text-foreground leading-relaxed">
        <div>
          <h2 className="text-lg font-bold mb-1">AI Formula Generator — EULA</h2>
          <p className="text-muted-foreground text-xs">Last updated: June 27, 2026</p>
        </div>

        <section className="space-y-2">
          <h3 className="font-bold text-base">1. Acceptance of Terms</h3>
          <p>By installing, accessing, or using the AI Formula Generator Excel Add-in ("the Software"), you agree to be bound by the terms of this End-User License Agreement ("EULA"). If you do not agree, do not use the Software.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">2. License Grant</h3>
          <p>Upon payment of the monthly subscription fee (1 USDT/month), you are granted a non-exclusive, non-transferable, worldwide license to use the Software for personal or commercial purposes for a period of 30 days from the date of payment. Access expires at the end of each billing period and must be renewed to continue use.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">3. Restrictions</h3>
          <p>You may not:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Resell, sublicense, or redistribute the Software or your license key</li>
            <li>Reverse-engineer, decompile, or disassemble the Software</li>
            <li>Use the Software for any unlawful purpose</li>
            <li>Share your license key with others</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">4. AI-Generated Content Disclaimer</h3>
          <p>The formulas generated by this Software are produced by an AI language model and are provided for informational purposes only. While we strive for accuracy, we do not guarantee that generated formulas will be error-free or suitable for every use case. You are responsible for verifying any formula before using it in a production environment.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">5. Payment & Refunds</h3>
          <p>All purchases are final. Because the Software grants immediate access to AI-generated content, refunds are not provided after a license key has been issued. In the event of a technical issue on our end, contact support within 7 days of purchase.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">6. Intellectual Property</h3>
          <p>The Software, including its source code, design, and documentation, is the intellectual property of the developer. Formulas generated for you by the Software may be used freely by you without restriction.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">7. Limitation of Liability</h3>
          <p>To the maximum extent permitted by law, the developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Software or reliance on AI-generated formulas.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">8. Termination</h3>
          <p>This license terminates automatically if you breach any term of this EULA. Upon termination, you must stop using the Software and destroy any copies in your possession.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">9. Changes to This Agreement</h3>
          <p>We reserve the right to update this EULA at any time. Continued use of the Software after changes are posted constitutes your acceptance of the revised terms.</p>
        </section>

        <section className="space-y-2">
          <h3 className="font-bold text-base">10. Contact</h3>
          <p>For questions regarding this EULA, please visit our <button onClick={() => setLocation("/support")} className="text-indigo-600 underline hover:no-underline">Support page</button>.</p>
        </section>

        <div className="pt-4 border-t border-border text-xs text-muted-foreground">
          AI Formula Generator · Excel Add-in
        </div>
      </main>
    </div>
  );
}
